// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtggqfnzjeqhopqouthv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0Z2dxZm56amVxaG9wcW91dGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTc3NDUsImV4cCI6MjA1ODU5Mzc0NX0._ulZsOJcKucn2X0Xi4c0JJfMGCB48fKFTdvfQiU3cko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);